Use of wrong operators in debian.pm caused "nodeset <node> install" to fail for provisioning an Ubuntu node for x86.  Error was:
    # nodeset <node> install
    Error: Install image not found in /install/ubuntu10.04.2/x86
    Error: Some nodes failed to set up install resources, aborting


git-svn-id: https://svn.code.sf.net/p/xcat/code/xcat-core/trunk@10298 8638fb3e-16cb-4fca-ae20-7b5d299a9bcd